version: '3.8'


services:
  bot:
    image: tg_bot
    build:
      context: .
    env_file:
      - .env
    environment:
      - POSTGRES_HOST=db
    restart: unless-stopped
    depends_on:
      - db
  db:
    image: tg_bot_db
    build:
      context: ./database
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - PGDATA=/var/lib/postgresql/data
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
