version: '3.0'

services:
  bot:
    container_name: bot
    build:
      context: .
    env_file:
      - .env
    volumes:
      - .:/app
    ports:
      - 5000:5000
    command: npm run prod
    restart: always
  auth-server:
    container_name: auth-server
    build:
      context: .
    env_file:
      - .env
    volumes:
      - .:/app
    ports:
      - 3000:3000
    command: npm run auth-server
    restart: always
